Added changes

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -194,15 +194,21 @@ jobs:
         id: apply
         continue-on-error: true  # allow failure so we can handle it manually
         run: | 
-          terraform apply -auto-approve tfplan > apply.txt
-          echo "exit_code=$?" >> $GITHUB_OUTPUT
-      
-      - name: Prepare apply output for comment
-        id: prepare-apply-output
-        run: |
+          terraform apply -auto-approve tfplan -no-color > apply.txt
           echo "TERRAFORM_APPLY_OUTPUT<<EOF" >> $GITHUB_OUTPUT
           cat apply.txt >> $GITHUB_OUTPUT
           echo "EOF" >> $GITHUB_OUTPUT
+          # Capture exit code
+          echo "exit_code=$?" >> $GITHUB_OUTPUT
+      
+      # - name: Prepare apply output for comment
+      #   id: prepare-apply-output
+      #   run: |
+      #       {
+      #         echo "TERRAFORM_APPLY_OUTPUT<<EOF"
+      #         cat apply.txt
+      #         echo "EOF"
+      #       } >> $GITHUB_OUTPUT
       
       
       - name: Comment Apply Output on GitHub Issue
@@ -215,7 +221,7 @@ jobs:
             <summary>Click to expand output</summary>
       
             ```
-            ${{ steps.prepare-apply-output.outputs.TERRAFORM_APPLY_OUTPUT }}
+            ${{ steps.apply.outputs.TERRAFORM_APPLY_OUTPUT }}
             ```
       
             </details>
@@ -233,7 +239,7 @@ jobs:
             });
           
       - name: Comment failure on GitHub issue
-        if: ${{ steps.apply.outputs.exit_code != '0' }}
+        if: ${{ steps.apply.outputs.exit_code != '0' }} # Only run if apply failed    
         uses: actions/github-script@v7
         with:
           script: |
